sudo: required
services:
   - docker

before_install:
    - docker build -t svangala/react-docker -f Dockerfile.dev .

script:
    - docker run svangala/react-docker npm run test -- --

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "name of the elasticbeanstalk app name"
    env: " "
    bucket_name:
    bucket_path: 
    on:
      branch: master
    
